version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guacpanel-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=guacpanel
      - DB_USERNAME=guacpanel
      - DB_PASSWORD=secret123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_API_KEY=xyz123
      - SCOUT_DRIVER=typesense
    ports:
      - "8080:80"
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    depends_on:
      - mysql
      - redis
      - typesense
    networks:
      - guacpanel-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: guacpanel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: guacpanel
      MYSQL_USER: guacpanel
      MYSQL_PASSWORD: secret123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - guacpanel-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: guacpanel-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - guacpanel-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5

  # Typesense Search Engine
  typesense:
    image: typesense/typesense:0.25.0
    container_name: guacpanel-typesense
    restart: unless-stopped
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz123
      TYPESENSE_ENABLE_CORS: "true"
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    networks:
      - guacpanel-network
    command: '--data-dir /data --api-key=xyz123 --enable-cors'

  # phpMyAdmin for Database Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: guacpanel-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: guacpanel
      PMA_PASSWORD: secret123
      UPLOAD_LIMIT: 100M
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - guacpanel-network

networks:
  guacpanel-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  typesense-data:
    driver: local